# Generated by Django 5.1.3 on 2024-12-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adumyl', '0003_menuitem_image_url_restaurant_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='schedule',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='days',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='operating_hours',
            field=models.TextField(blank=True, null=True),
        ),
    ]
