# Generated by Django 5.1.3 on 2024-12-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adumyl', '0004_remove_restaurant_schedule_restaurant_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_sales',
            field=models.IntegerField(default=0),
        ),
    ]
