# Generated by Django 5.1.3 on 2024-12-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adumyl', '0005_user_total_orders_user_total_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='total_orders',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_sales',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='total_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='total_sales',
            field=models.IntegerField(default=0),
        ),
    ]
