# Generated by Django 5.1.3 on 2024-12-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adumyl', '0006_remove_user_total_orders_remove_user_total_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='vehicle',
            field=models.CharField(default='car', max_length=255),
        ),
    ]
