# Generated by Django 5.1.3 on 2024-12-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adumyl', '0007_courier_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='current_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
