# Generated by Django 5.1.3 on 2024-12-27 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adumyl', '0007_courier_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='current_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('restaurant_coordinates', models.JSONField()),
                ('delivery_coordinates', models.JSONField()),
                ('restaurant_address', models.TextField()),
                ('delivery_address', models.TextField()),
                ('stages', models.JSONField(default=list)),
                ('current_stage', models.PositiveIntegerField(default=0)),
                ('estimated_time', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_agent',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   to='adumyl.courier')),
            ],
        ),
    ]

